# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: push
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 15.x
      uses: actions/setup-node@v2
      with:
        node-version: 15.x
    - name: Install Yarn
      run: npm install -g yarn    
    - run: yarn install
    - run: yarn run build --if-present
    - run: yarn test --watchAll=false --coverage
    - uses: actions/upload-artifact@v1
      with:
        name: lcov.info
        path: ./coverage/lcov.info
    - uses: actions/cache@v2
      with:
        path: ./coverage/lcov.info
        key: cov.info
  deploy:
      name: Deploy with metrics
      runs-on: ubuntu-latest
      needs: [build]
      steps:
        - uses: actions/cache@v2
          with:
            path: ./coverage/lcov.info
            key: cov.info
        - uses: codecov/codecov-action@v1
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            file: ./coverage/lcov.info
        - name: Invoke deployment hook
          uses: distributhor/workflow-webhook@v1
          env:
            webhook_url: ${{ secrets.WEBHOOK_URL }}
            webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
        - name: Wait during 2 minutes
          uses: jakejarvis/wait-action@master
          with:
            time: '120s'
        - name: Audit live URL
          uses: jakejarvis/lighthouse-action@master
          with:
            url: 'https://front.safely-app.fr/'
        - name: Upload results as an artifact
          uses: actions/upload-artifact@master
          with:
            name: report
            path: './report'
