# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 15.x
      uses: actions/setup-node@v2
      with:
        node-version: 15.x
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
  deploy:
      name: Deploy with metrics
      runs-on: ubuntu-latest
      #needs: [build]
      steps:
        - name: Quickmetrics
          uses: screendriver/quickmetrics-action@v1
          with:
            name: fake-deploy-front
            api-key: ${{ secrets.QUICKMETRICS_API_KEY }}
        - name: Invoke deployment hook
          uses: distributhor/workflow-webhook@v1
          env:
            webhook_url: ${{ secrets.WEBHOOK_URL }}
            webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
        - name: Wait during 2 minutes
          uses: jakejarvis/wait-action@master
          with:
            time: '120s'
        - name: Audit live URL
          uses: jakejarvis/lighthouse-action@master
          with:
            url: 'https://front.safely-app.fr/'
        - name: Upload results as an artifact
          uses: actions/upload-artifact@master
          with:
            name: report
            path: './report'
