# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
  fake_deploy:
      name: Fake deploy with metrics
      runs-on: ubuntu-latest
      needs: [build]
      steps:
        - name: Quickmetrics
          uses: screendriver/quickmetrics-action@v1
          with:
            name: pull-request-front
            api-key: ${{ secrets.QUICKMETRICS_API_KEY }}
        #- name: Discord notification
        #  env:
        #    DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        #  uses: Ilshidur/action-discord@master
        #  with:
        #    args: 'New pull request for webapp.'
